/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use reqwest;

use super::{Error, configuration};

pub struct ConferencesApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl ConferencesApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> ConferencesApiClient {
        ConferencesApiClient {
            configuration: configuration,
        }
    }
}

pub trait ConferencesApi {
    fn get_conference(&self, id: f32) -> Result<crate::models::Division, Error>;
    fn get_conferences(&self, ) -> Result<crate::models::Conferences, Error>;
}

impl ConferencesApi for ConferencesApiClient {
    fn get_conference(&self, id: f32) -> Result<crate::models::Division, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/conferences/{id}", configuration.base_path, id=id);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_conferences(&self, ) -> Result<crate::models::Conferences, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/conferences", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

}
