/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use reqwest;

use super::{Error, configuration};

pub struct PlayersApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl PlayersApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> PlayersApiClient {
        PlayersApiClient {
            configuration: configuration,
        }
    }
}

pub trait PlayersApi {
    fn get_player(&self, id: f32) -> Result<crate::models::Players, Error>;
    fn get_player_stats(&self, id: f32, stats: &str, season: f32) -> Result<crate::models::PlayerStats, Error>;
}

impl PlayersApi for PlayersApiClient {
    fn get_player(&self, id: f32) -> Result<crate::models::Players, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/people/{id}", configuration.base_path, id=id);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_player_stats(&self, id: f32, stats: &str, season: f32) -> Result<crate::models::PlayerStats, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/people/{id}/stats", configuration.base_path, id=id);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("stats", &stats.to_string())]);
        req_builder = req_builder.query(&[("season", &season.to_string())]);
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

}
