/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct DraftApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> DraftApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> DraftApiClient<C> {
        DraftApiClient {
            configuration: configuration,
        }
    }
}

pub trait DraftApi {
    fn get_draft(&self, ) -> Box<Future<Item = crate::models::Draft, Error = Error<serde_json::Value>>>;
    fn get_draft_by_year(&self, year: f32) -> Box<Future<Item = crate::models::Draft, Error = Error<serde_json::Value>>>;
    fn get_draft_prospect(&self, id: f32) -> Box<Future<Item = crate::models::DraftProspects, Error = Error<serde_json::Value>>>;
    fn get_draft_prospects(&self, ) -> Box<Future<Item = crate::models::DraftProspects, Error = Error<serde_json::Value>>>;
}


impl<C: hyper::client::Connect>DraftApi for DraftApiClient<C> {
    fn get_draft(&self, ) -> Box<Future<Item = crate::models::Draft, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Get, "/draft".to_string())
            .execute(self.configuration.borrow())
    }

    fn get_draft_by_year(&self, year: f32) -> Box<Future<Item = crate::models::Draft, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Get, "/draft/{year}".to_string())
            .with_path_param("year".to_string(), year.to_string())
            .execute(self.configuration.borrow())
    }

    fn get_draft_prospect(&self, id: f32) -> Box<Future<Item = crate::models::DraftProspects, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Get, "/draft/prospects/{id}".to_string())
            .with_path_param("id".to_string(), id.to_string())
            .execute(self.configuration.borrow())
    }

    fn get_draft_prospects(&self, ) -> Box<Future<Item = crate::models::DraftProspects, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Get, "/draft/prospects".to_string())
            .execute(self.configuration.borrow())
    }

}
