/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Draft {
    #[serde(rename = "copyright", skip_serializing_if = "Option::is_none")]
    pub copyright: Option<String>,
    #[serde(rename = "drafts", skip_serializing_if = "Option::is_none")]
    pub drafts: Option<Vec<crate::models::DraftDrafts>>,
}

impl Draft {
    pub fn new() -> Draft {
        Draft {
            copyright: None,
            drafts: None,
        }
    }
}


