/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct DraftDrafts {
    #[serde(rename = "draftYear", skip_serializing_if = "Option::is_none")]
    pub draft_year: Option<f32>,
    #[serde(rename = "rounds", skip_serializing_if = "Option::is_none")]
    pub rounds: Option<Vec<crate::models::DraftRounds>>,
}

impl DraftDrafts {
    pub fn new() -> DraftDrafts {
        DraftDrafts {
            draft_year: None,
            rounds: None,
        }
    }
}


