/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub enum EnumStatTypes {
    #[serde(rename = "byDayOfWeek")]
    ByDayOfWeek,
    #[serde(rename = "byDayOfWeekPlayoffs")]
    ByDayOfWeekPlayoffs,
    #[serde(rename = "byMonth")]
    ByMonth,
    #[serde(rename = "byMonthPlayoffs")]
    ByMonthPlayoffs,
    #[serde(rename = "careerPlayoffs")]
    CareerPlayoffs,
    #[serde(rename = "careerRegularSeason")]
    CareerRegularSeason,
    #[serde(rename = "gameLog")]
    GameLog,
    #[serde(rename = "goalsByGameSituation")]
    GoalsByGameSituation,
    #[serde(rename = "goalsByGameSituationPlayoffs")]
    GoalsByGameSituationPlayoffs,
    #[serde(rename = "homeAndAway")]
    HomeAndAway,
    #[serde(rename = "homeAndAwayPlayoffs")]
    HomeAndAwayPlayoffs,
    #[serde(rename = "onPaceRegularSeason")]
    OnPaceRegularSeason,
    #[serde(rename = "playoffGameLog")]
    PlayoffGameLog,
    #[serde(rename = "playoffStatRankings")]
    PlayoffStatRankings,
    #[serde(rename = "regularSeasonStatRankings")]
    RegularSeasonStatRankings,
    #[serde(rename = "statsSingleSeason")]
    StatsSingleSeason,
    #[serde(rename = "statsSingleSeasonPlayoffs")]
    StatsSingleSeasonPlayoffs,
    #[serde(rename = "vsConference")]
    VsConference,
    #[serde(rename = "vsConferencePlayoffs")]
    VsConferencePlayoffs,
    #[serde(rename = "vsDivision")]
    VsDivision,
    #[serde(rename = "vsDivisionPlayoffs")]
    VsDivisionPlayoffs,
    #[serde(rename = "vsTeam")]
    VsTeam,
    #[serde(rename = "vsTeamPlayoffs")]
    VsTeamPlayoffs,
    #[serde(rename = "winLoss")]
    WinLoss,
    #[serde(rename = "winLossPlayoffs")]
    WinLossPlayoffs,
    #[serde(rename = "yearByYear")]
    YearByYear,
    #[serde(rename = "yearByYearPlayoffs")]
    YearByYearPlayoffs,
    #[serde(rename = "yearByYearPlayoffsRank")]
    YearByYearPlayoffsRank,
    #[serde(rename = "yearByYearRank")]
    YearByYearRank,

}



