/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub enum EnumExpandSchedule {
    #[serde(rename = "schedule.broadcasts")]
    Broadcasts,
    #[serde(rename = "schedule.linescore")]
    Linescore,
    #[serde(rename = "schedule.ticket")]
    Ticket,

}



