/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GameBoxscoreTeamCoaches {
    #[serde(rename = "person", skip_serializing_if = "Option::is_none")]
    pub person: Option<crate::models::GameBoxscoreTeamPerson>,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<crate::models::GameBoxscoreTeamPosition>,
}

impl GameBoxscoreTeamCoaches {
    pub fn new() -> GameBoxscoreTeamCoaches {
        GameBoxscoreTeamCoaches {
            person: None,
            position: None,
        }
    }
}


