/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GameLinescore {
    #[serde(rename = "currentPeriod", skip_serializing_if = "Option::is_none")]
    pub current_period: Option<f32>,
    #[serde(rename = "currentPeriodOrdinal", skip_serializing_if = "Option::is_none")]
    pub current_period_ordinal: Option<String>,
    #[serde(rename = "currentPeriodTimeRemaining", skip_serializing_if = "Option::is_none")]
    pub current_period_time_remaining: Option<String>,
    #[serde(rename = "periods", skip_serializing_if = "Option::is_none")]
    pub periods: Option<Vec<crate::models::GamePeriod>>,
    #[serde(rename = "shootoutInfo", skip_serializing_if = "Option::is_none")]
    pub shootout_info: Option<crate::models::GameLinescoreShootoutInfo>,
    #[serde(rename = "teams", skip_serializing_if = "Option::is_none")]
    pub teams: Option<crate::models::GameLinescoreTeams>,
    #[serde(rename = "powerPlayStrength", skip_serializing_if = "Option::is_none")]
    pub power_play_strength: Option<String>,
    #[serde(rename = "hasShootout", skip_serializing_if = "Option::is_none")]
    pub has_shootout: Option<bool>,
    #[serde(rename = "intermissionInfo", skip_serializing_if = "Option::is_none")]
    pub intermission_info: Option<crate::models::GameLinescoreIntermissionInfo>,
    #[serde(rename = "powerPlayInfo", skip_serializing_if = "Option::is_none")]
    pub power_play_info: Option<crate::models::GameLinescorePowerPlayInfo>,
}

impl GameLinescore {
    pub fn new() -> GameLinescore {
        GameLinescore {
            current_period: None,
            current_period_ordinal: None,
            current_period_time_remaining: None,
            periods: None,
            shootout_info: None,
            teams: None,
            power_play_strength: None,
            has_shootout: None,
            intermission_info: None,
            power_play_info: None,
        }
    }
}


