/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GameLinescoreIntermissionInfo {
    #[serde(rename = "intermissionTimeRemaining", skip_serializing_if = "Option::is_none")]
    pub intermission_time_remaining: Option<f32>,
    #[serde(rename = "intermissionTimeElapsed", skip_serializing_if = "Option::is_none")]
    pub intermission_time_elapsed: Option<f32>,
    #[serde(rename = "inIntermission", skip_serializing_if = "Option::is_none")]
    pub in_intermission: Option<bool>,
}

impl GameLinescoreIntermissionInfo {
    pub fn new() -> GameLinescoreIntermissionInfo {
        GameLinescoreIntermissionInfo {
            intermission_time_remaining: None,
            intermission_time_elapsed: None,
            in_intermission: None,
        }
    }
}


