/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GameMetaData {
    #[serde(rename = "wait", skip_serializing_if = "Option::is_none")]
    pub wait: Option<f32>,
    #[serde(rename = "timeStamp", skip_serializing_if = "Option::is_none")]
    pub time_stamp: Option<String>,
}

impl GameMetaData {
    pub fn new() -> GameMetaData {
        GameMetaData {
            wait: None,
            time_stamp: None,
        }
    }
}


