/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GameLinescoreShootoutInfoAway {
    #[serde(rename = "scores", skip_serializing_if = "Option::is_none")]
    pub scores: Option<f32>,
    #[serde(rename = "attempts", skip_serializing_if = "Option::is_none")]
    pub attempts: Option<f32>,
}

impl GameLinescoreShootoutInfoAway {
    pub fn new() -> GameLinescoreShootoutInfoAway {
        GameLinescoreShootoutInfoAway {
            scores: None,
            attempts: None,
        }
    }
}


