/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GamePlayAboutGoals {
    #[serde(rename = "away", skip_serializing_if = "Option::is_none")]
    pub away: Option<f32>,
    #[serde(rename = "home", skip_serializing_if = "Option::is_none")]
    pub home: Option<f32>,
}

impl GamePlayAboutGoals {
    pub fn new() -> GamePlayAboutGoals {
        GamePlayAboutGoals {
            away: None,
            home: None,
        }
    }
}


