/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GameContentMediaMilestones {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<Title>,
    #[serde(rename = "streamStart", skip_serializing_if = "Option::is_none")]
    pub stream_start: Option<String>,
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::GameContentMediaMilestonesItems>>,
}

impl GameContentMediaMilestones {
    pub fn new() -> GameContentMediaMilestones {
        GameContentMediaMilestones {
            title: None,
            stream_start: None,
            items: None,
        }
    }
}

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum Title {
    #[serde(rename = "Milestones")]
    Milestones,
}

