/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GamePlayCoordinates {
    #[serde(rename = "x", skip_serializing_if = "Option::is_none")]
    pub x: Option<f32>,
    #[serde(rename = "y", skip_serializing_if = "Option::is_none")]
    pub y: Option<f32>,
}

impl GamePlayCoordinates {
    pub fn new() -> GamePlayCoordinates {
        GamePlayCoordinates {
            x: None,
            y: None,
        }
    }
}


