/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GamePeriodAway {
    #[serde(rename = "goals", skip_serializing_if = "Option::is_none")]
    pub goals: Option<f32>,
    #[serde(rename = "shotsOnGoal", skip_serializing_if = "Option::is_none")]
    pub shots_on_goal: Option<f32>,
    #[serde(rename = "rinkSide", skip_serializing_if = "Option::is_none")]
    pub rink_side: Option<String>,
}

impl GamePeriodAway {
    pub fn new() -> GamePeriodAway {
        GamePeriodAway {
            goals: None,
            shots_on_goal: None,
            rink_side: None,
        }
    }
}


