/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GameGameDataGame {
    #[serde(rename = "pk", skip_serializing_if = "Option::is_none")]
    pub pk: Option<f32>,
    #[serde(rename = "season", skip_serializing_if = "Option::is_none")]
    pub season: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl GameGameDataGame {
    pub fn new() -> GameGameDataGame {
        GameGameDataGame {
            pk: None,
            season: None,
            _type: None,
        }
    }
}


