/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GameBoxscoreTeamTeamStats {
    #[serde(rename = "teamSkaterStats", skip_serializing_if = "Option::is_none")]
    pub team_skater_stats: Option<crate::models::GameBoxscoreTeamTeamStatsTeamSkaterStats>,
}

impl GameBoxscoreTeamTeamStats {
    pub fn new() -> GameBoxscoreTeamTeamStats {
        GameBoxscoreTeamTeamStats {
            team_skater_stats: None,
        }
    }
}


