/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GamePlay {
    #[serde(rename = "players", skip_serializing_if = "Option::is_none")]
    pub players: Option<Vec<crate::models::GamePlayPlayers>>,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<crate::models::GamePlayResult>,
    #[serde(rename = "about", skip_serializing_if = "Option::is_none")]
    pub about: Option<crate::models::GamePlayAbout>,
    #[serde(rename = "coordinates", skip_serializing_if = "Option::is_none")]
    pub coordinates: Option<crate::models::GamePlayCoordinates>,
    #[serde(rename = "team", skip_serializing_if = "Option::is_none")]
    pub team: Option<crate::models::GamePlayTeam>,
}

impl GamePlay {
    pub fn new() -> GamePlay {
        GamePlay {
            players: None,
            result: None,
            about: None,
            coordinates: None,
            team: None,
        }
    }
}


