/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GameHighlightPlaybacks {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Name>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<String>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl GameHighlightPlaybacks {
    pub fn new() -> GameHighlightPlaybacks {
        GameHighlightPlaybacks {
            name: None,
            width: None,
            height: None,
            url: None,
        }
    }
}

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "FLASH_192K_320X180")]
    FLASH192K320X180,
    #[serde(rename = "FLASH_450K_400X224")]
    FLASH450K400X224,
    #[serde(rename = "FLASH_1200K_640X360")]
    FLASH1200K640X360,
    #[serde(rename = "FLASH_1800K_960X540")]
    FLASH1800K960X540,
    #[serde(rename = "HTTP_CLOUD_MOBILE")]
    HTTPCLOUDMOBILE,
    #[serde(rename = "HTTP_CLOUD_TABLET")]
    HTTPCLOUDTABLET,
    #[serde(rename = "HTTP_CLOUD_TABLET_60")]
    HTTPCLOUDTABLET60,
    #[serde(rename = "HTTP_CLOUD_WIRED")]
    HTTPCLOUDWIRED,
    #[serde(rename = "HTTP_CLOUD_WIRED_60")]
    HTTPCLOUDWIRED60,
    #[serde(rename = "HTTP_CLOUD_WIRED_WEB")]
    HTTPCLOUDWIREDWEB,
}

