/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GameBoxscoreTeamPlayersStats {
    #[serde(rename = "skaterStats", skip_serializing_if = "Option::is_none")]
    pub skater_stats: Option<crate::models::GameBoxscoreTeamPlayersStatsSkaterStats>,
}

impl GameBoxscoreTeamPlayersStats {
    pub fn new() -> GameBoxscoreTeamPlayersStats {
        GameBoxscoreTeamPlayersStats {
            skater_stats: None,
        }
    }
}


