/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GameBoxscores {
    #[serde(rename = "copyright", skip_serializing_if = "Option::is_none")]
    pub copyright: Option<String>,
    #[serde(rename = "teams", skip_serializing_if = "Option::is_none")]
    pub teams: Option<crate::models::GameBoxscoreTeams>,
    #[serde(rename = "officials", skip_serializing_if = "Option::is_none")]
    pub officials: Option<Vec<crate::models::GameOfficial>>,
}

impl GameBoxscores {
    pub fn new() -> GameBoxscores {
        GameBoxscores {
            copyright: None,
            teams: None,
            officials: None,
        }
    }
}


