/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GameBoxscoreTeamTeam {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<f32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    #[serde(rename = "abbreviation", skip_serializing_if = "Option::is_none")]
    pub abbreviation: Option<String>,
    #[serde(rename = "triCode", skip_serializing_if = "Option::is_none")]
    pub tri_code: Option<String>,
}

impl GameBoxscoreTeamTeam {
    pub fn new() -> GameBoxscoreTeamTeam {
        GameBoxscoreTeamTeam {
            id: None,
            name: None,
            link: None,
            abbreviation: None,
            tri_code: None,
        }
    }
}


