/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct GameEditorialContributorContributors {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "twitter", skip_serializing_if = "Option::is_none")]
    pub twitter: Option<String>,
}

impl GameEditorialContributorContributors {
    pub fn new() -> GameEditorialContributorContributors {
        GameEditorialContributorContributors {
            name: None,
            twitter: None,
        }
    }
}


