/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Players {
    #[serde(rename = "copyright")]
    pub copyright: String,
    #[serde(rename = "teams", skip_serializing_if = "Option::is_none")]
    pub teams: Option<Vec<crate::models::Player>>,
}

impl Players {
    pub fn new(copyright: String) -> Players {
        Players {
            copyright: copyright,
            teams: None,
        }
    }
}


