/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleGameTickets {
    #[serde(rename = "ticketType", skip_serializing_if = "Option::is_none")]
    pub ticket_type: Option<TicketType>,
    #[serde(rename = "ticketLink", skip_serializing_if = "Option::is_none")]
    pub ticket_link: Option<String>,
}

impl ScheduleGameTickets {
    pub fn new() -> ScheduleGameTickets {
        ScheduleGameTickets {
            ticket_type: None,
            ticket_link: None,
        }
    }
}

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum TicketType {
    #[serde(rename = "buysell")]
    Buysell,
    #[serde(rename = "club buysell")]
    Club_buysell,
    #[serde(rename = "club mobile")]
    Club_mobile,
    #[serde(rename = "club mobile buysell")]
    Club_mobile_buysell,
    #[serde(rename = "club ticket")]
    Club_ticket,
    #[serde(rename = "mobile app ticket")]
    Mobile_app_ticket,
    #[serde(rename = "mobile buysell")]
    Mobile_buysell,
    #[serde(rename = "mobile ticket")]
    Mobile_ticket,
    #[serde(rename = "tablet app ticket")]
    Tablet_app_ticket,
    #[serde(rename = "ticket")]
    Ticket,
}

