/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleGame {
    #[serde(rename = "gamePk", skip_serializing_if = "Option::is_none")]
    pub game_pk: Option<f32>,
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    #[serde(rename = "gameType", skip_serializing_if = "Option::is_none")]
    pub game_type: Option<String>,
    #[serde(rename = "season", skip_serializing_if = "Option::is_none")]
    pub season: Option<String>,
    #[serde(rename = "gameDate", skip_serializing_if = "Option::is_none")]
    pub game_date: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::GameGameDataStatus>,
    #[serde(rename = "teams", skip_serializing_if = "Option::is_none")]
    pub teams: Option<crate::models::ScheduleGameTeams>,
    #[serde(rename = "linescore", skip_serializing_if = "Option::is_none")]
    pub linescore: Option<crate::models::GameLinescore>,
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<crate::models::GameGameDataVenue>,
    #[serde(rename = "tickets", skip_serializing_if = "Option::is_none")]
    pub tickets: Option<Vec<crate::models::ScheduleGameTickets>>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<crate::models::ScheduleGameContent>,
}

impl ScheduleGame {
    pub fn new() -> ScheduleGame {
        ScheduleGame {
            game_pk: None,
            link: None,
            game_type: None,
            season: None,
            game_date: None,
            status: None,
            teams: None,
            linescore: None,
            venue: None,
            tickets: None,
            content: None,
        }
    }
}


