/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct StandingTypes {
    #[serde(rename = "records", skip_serializing_if = "Option::is_none", flatten)]
    pub records: Option<Vec<crate::models::StandingTypesRecords>>,
}

impl StandingTypes {
    pub fn new() -> StandingTypes {
        StandingTypes {
            records: None,
        }
    }
}


