/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct StandingTypesRecords {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<crate::models::EnumStandingTypes>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl StandingTypesRecords {
    pub fn new() -> StandingTypesRecords {
        StandingTypesRecords {
            name: None,
            description: None,
        }
    }
}


