/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct StandingsTeamRecords {
    #[serde(rename = "team", skip_serializing_if = "Option::is_none")]
    pub team: Option<crate::models::PlayerCurrentTeam>,
    #[serde(rename = "leagueRecord", skip_serializing_if = "Option::is_none")]
    pub league_record: Option<crate::models::ScheduleGameTeamsHomeLeagueRecord>,
    #[serde(rename = "goalsAgainst", skip_serializing_if = "Option::is_none")]
    pub goals_against: Option<f32>,
    #[serde(rename = "goalsScored", skip_serializing_if = "Option::is_none")]
    pub goals_scored: Option<f32>,
    #[serde(rename = "points", skip_serializing_if = "Option::is_none")]
    pub points: Option<f32>,
    #[serde(rename = "divisionRank", skip_serializing_if = "Option::is_none")]
    pub division_rank: Option<String>,
    #[serde(rename = "conferenceRank", skip_serializing_if = "Option::is_none")]
    pub conference_rank: Option<String>,
    #[serde(rename = "leagueRank", skip_serializing_if = "Option::is_none")]
    pub league_rank: Option<String>,
    #[serde(rename = "wildCardRank", skip_serializing_if = "Option::is_none")]
    pub wild_card_rank: Option<String>,
    #[serde(rename = "row", skip_serializing_if = "Option::is_none")]
    pub row: Option<f32>,
    #[serde(rename = "gamesPlayed", skip_serializing_if = "Option::is_none")]
    pub games_played: Option<f32>,
    #[serde(rename = "streak", skip_serializing_if = "Option::is_none")]
    pub streak: Option<crate::models::StandingsStreak>,
    #[serde(rename = "lastUpdated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
}

impl StandingsTeamRecords {
    pub fn new() -> StandingsTeamRecords {
        StandingsTeamRecords {
            team: None,
            league_record: None,
            goals_against: None,
            goals_scored: None,
            points: None,
            division_rank: None,
            conference_rank: None,
            league_rank: None,
            wild_card_rank: None,
            row: None,
            games_played: None,
            streak: None,
            last_updated: None,
        }
    }
}


