/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct StandingsStreak {
    #[serde(rename = "streakType", skip_serializing_if = "Option::is_none")]
    pub streak_type: Option<String>,
    #[serde(rename = "streakNumber", skip_serializing_if = "Option::is_none")]
    pub streak_number: Option<f32>,
    #[serde(rename = "streakCode", skip_serializing_if = "Option::is_none")]
    pub streak_code: Option<String>,
}

impl StandingsStreak {
    pub fn new() -> StandingsStreak {
        StandingsStreak {
            streak_type: None,
            streak_number: None,
            streak_code: None,
        }
    }
}


