/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamNextGameScheduleTeamsHome {
    #[serde(rename = "leagueRecord", skip_serializing_if = "Option::is_none")]
    pub league_record: Option<crate::models::TeamNextGameScheduleTeamsHomeLeagueRecord>,
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f32>,
    #[serde(rename = "team", skip_serializing_if = "Option::is_none")]
    pub team: Option<crate::models::PlayerCurrentTeam>,
}

impl TeamNextGameScheduleTeamsHome {
    pub fn new() -> TeamNextGameScheduleTeamsHome {
        TeamNextGameScheduleTeamsHome {
            league_record: None,
            score: None,
            team: None,
        }
    }
}


