/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamStatsStatsSplits {
    #[serde(rename = "stat", skip_serializing_if = "Option::is_none", flatten)]
    pub stat: Option<crate::models::AnyOfTeamStatsValuesTeamStatsRankings>,
    #[serde(rename = "team", skip_serializing_if = "Option::is_none")]
    pub team: Option<crate::models::PlayerCurrentTeam>,
}

impl TeamStatsStatsSplits {
    pub fn new() -> TeamStatsStatsSplits {
        TeamStatsStatsSplits {
            stat: None,
            team: None,
        }
    }
}


#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum AnyOfTeamStatsValuesTeamStatsRankings {
    Values(super::TeamStatsValues),
    Rankings(super::TeamStatsRankings),
}
