/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamStatsSplits {
    #[serde(rename = "stat", skip_serializing_if = "Option::is_none")]
    pub stat: Option<crate::models::TeamStatsStat>,
    #[serde(rename = "team", skip_serializing_if = "Option::is_none")]
    pub team: Option<crate::models::PlayerCurrentTeam>,
}

impl TeamStatsSplits {
    pub fn new() -> TeamStatsSplits {
        TeamStatsSplits {
            stat: None,
            team: None,
        }
    }
}


