/*
 * NHL API
 *
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct VenueTimeZone {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<f32>,
    #[serde(rename = "tz", skip_serializing_if = "Option::is_none")]
    pub tz: Option<String>,
}

impl VenueTimeZone {
    pub fn new() -> VenueTimeZone {
        VenueTimeZone {
            id: None,
            offset: None,
            tz: None,
        }
    }
}


